site_name: Wholepaper
site_description: Wallpaper for your desktop and browser, in one place.
docs_dir: docs

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - search.highlight
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- tables
- pymdownx.snippets:
    base_path: .
- toc:
    permalink: true

extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascript/tablesort.js

plugins:
- search
- awesome-nav
- table-reader
